# Generated by Django 2.2.6 on 2019-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nbre_habitant', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Population',
                'verbose_name_plural': 'Population',
            },
        ),
    ]
